name: Deployment pipeline

env:
  CONDITION: ${{ !contains(github.event.head_commit.message, '#skip') && github.event_name == 'push' && github.ref == 'refs/heads/main' }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - if: ${{ env.CONDITION == 'true' }}
        name: Checkout repository
        uses: actions/checkout@v4

      - if: ${{ env.CONDITION == 'true' }}
        name: Render Deployment
        uses: sws2apps/render-deployment@v1.8.0
        with:
          serviceId: ${{ secrets.SERVICE_ID }}
          apiKey: ${{ secrets.API_KEY }}
          multipleDeployment: false
      
      - name: A new version of Pokedex deployed
        uses: BubbleProd/discord-webhook-notify@v2.0.1
        if: ${{ success() }}
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Build failed
        uses: BubbleProd/discord-webhook-notify@v2.0.1
        if: ${{ failure() }}
        with:
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}



  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - if: ${{ env.CONDITION == 'true' }}
        name: Checkout repository
        uses: actions/checkout@v4
        
      - if: ${{ env.CONDITION == 'true' }}
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
